### ISSUE TITLE
Add new splunk/splunk-metrics-and-events integration

### ISSUE THREAD

**Issue by calebhailey** [sensu/catalog#108]
TODO: 

- [ ] Init integration from template (see: https://github.com/sensu/catalog/blob/main/templates)
  - [ ] Add `README.md`
  - [ ] Add `sensu-integration.yaml`
  - [ ] Add `CHANGELOG.md`
- [ ] Add `logo.png`
- [ ] Add `sensu-resources.yaml`
  - [ ] [splunk/splunk_tcp](https://github.com/sensu/catalog/tree/ch/flatten-the-catalog/integrations/splunk/splunk_tcp.yaml)
  - [ ] add a pipeline resource (example: [pagerduty/pagerduty-incidents](https://github.com/sensu/catalog/blob/main/integrations/pagerduty/pagerduty-incidents/sensu-resources.yaml#L1-L21))
  - [ ] move configured filters and mutators (if any) from handler(s) to the pipeline resource

**Comment by c-kruse** [comment]
@calebhailey  Is it okay to make this an enterprise-only integration? The current example is using the legacy tcp type handler. Moving it to a pipeline would mean migrating to the enterprise only pipeline/v1.TCPStreamHandler or writing a new splunk handler
