### ISSUE TITLE
Add new servicenow/servicenow-cmdb integration

### ISSUE THREAD

**Issue by calebhailey** [sensu/catalog#114]
TODO: 

- [ ] Init integration from template (see: https://github.com/sensu/catalog/blob/main/templates)
  - [ ] Add `README.md`
  - [ ] Add `sensu-integration.yaml`
  - [ ] Add `CHANGELOG.md`
- [ ] Add `logo.png`
- [ ] Add `sensu-resources.yaml`
  - [ ] [servicenow/servicenow-cmdb](https://github.com/sensu/catalog/tree/ch/flatten-the-catalog/integrations/servicenow/servicenow-cmdb.yaml)

**Comment by portertech** [comment]
Relevant open PR https://github.com/sensu/sensu-servicenow-handler/pull/43
