### ISSUE TITLE
Add new prometheus/node_exporter integration(s)

### ISSUE THREAD

**Issue by calebhailey** [sensu/catalog#181]
TODO: 

- [ ] Init integration from template (see: https://github.com/sensu/catalog/blob/main/templates)
  - [ ] Add `README.md`
  - [ ] Add `sensu-integration.yaml`
  - [ ] Add `CHANGELOG.md`
- [ ] Add `logo.png`
- [ ] Add `sensu-resources.yaml`

Notes: 

- Reference for `sensu-resources.yaml`: https://github.com/sensu/catalog/tree/ch/flatten-the-catalog/integrations/node_exporter/node_exporter.yaml
- Note that this example assumes availability of `wget`; what's a cross-platform alternative? Should we add an http-get command to https://github.com/sensu/http-checks?

**Comment by thoward** [comment]
Note, PR #187 closes this.
